name: 'Pin with Pinata'
description: 'Pin content to the IPFS using Pinata.'
inputs:
  pinata-api-key:
    description: 'Your Pinata API key.'
    required: true
  pinata-secret-api-key:
    description: 'Your Pinata Secret API key.'
    required: true
  file-to-pin:
    description: 'Path to the file or directory that you want to pin.'
    required: true
outputs:
  hash:
    description: 'The hash of the pinned file.'
  pinSize:
    description: 'The size, in MB, of the pinned hash.'
  timestamp:
    description: "The timestamp the hash was added to Pinata's pin queue."
runs:
  using: 'node16'
  main: 'dist/index.js'
